# Person-based notification configuration
audiences:
  jeremy:
    services:
      - notify.mobile_app_jeremy_phone
      - notify.jeremy_laptop
    min_severity: info
  
  sarah:
    services:
      - notify.mobile_app_sarah_phone
    min_severity: warning

  household:
    services:
      - notify.living_room_speaker
    min_severity: critical

# Severity levels from lowest to highest
severity_levels: [info, warning, critical]
